#+TITLE: 2020-08-03

* Constellations

La vie continue, c'est épuisant. Le sommeil est la seule arme qui
défait la conscience mais on s'endort trop souvent, et souvent trop
longtemps. Je suis fatigué, mais je ne sais de quoi. Peut-être
l'exaltation musicale de hier soir.

Le bruit me fatigue. Ce n'est pas la Nausée mais c'est sûrement la
première marche. Toutes ces conversations, tout ce monde qui
s'agite. Toujours quemandé pour des clopes, de l'esprit.

-----

Il faut bien s'entourer. Tout seul ça me paraît trop dur. Ça doit être
encore plus dur d'être seul quand on ne sait pas l'être; quand on
manque de curiosité et de rigueur car les deux vont de pair : il faut
être rigoureux pour s'offrir l'aventure de la curiosité. Sinon c'est
effectivement un vilain défaut.

Et il faut écrire sans peur d'être lu. J'en souffre mais je
progresse. Comme le disait si bien Martin: "à la fin de ma vie
j'espère dire que j'ai changé".

Sans changement, à quoi ça sert ? Le changement est un rouleau qu'il
faut surfer avec l'absurdité du Zen; de toute façon, il ne s'explique
pas. Avec toutes les certitudes du monde ou l'appui de la science, on
ne fait qu'encadrer le changement. On le mesure, ni plus ni moins.

-----

La souffrance de l'homme c'est de cribler le ciel de constellations
pour s'y sentir ancré. L'égotrip de la molécule de carbone qui cherche
à justifier son existence. Discerner c'est choisir, choisir c'est
renoncer.

L'inter-legere porte le poids du monde sur ses épaules frêles. Une
figure apparaît, une lumière brille dans le noir, on se console enfin
d'avoir choisi un sens. L'esprit s'accorde un moment de repos, on pèse
moins lourd. Plus tard on y retourne, et les sensations
tourbillonnent. Vertige grand vertige, des fois c'est l'adrénaline qui
en dissout l'essence. Puis elle s'épuise, c'est le grand silence.

On regarde autour, souvent dedans. "Tout cela a un sens", c'est le feu
de camp de notre humanité.
